<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
    <style>
        .timeline-with-icons {
            border-left: 1px solid hsl(0, 0%, 90%);
            position: relative;
            list-style: none;
        }

        .timeline-with-icons .timeline-item {
            position: relative;
        }

        .timeline-with-icons .timeline-item:after {
            position: absolute;
            display: block;
            top: 0;
        }

        .timeline-with-icons .timeline-icon {
            position: absolute;
            left: -48px;
            background-color: hsl(217, 88.2%, 90%);
            color: hsl(217, 88.8%, 35.1%);
            border-radius: 50%;
            height: 31px;
            width: 31px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <div class="row">

                        <div class="col-md-6">

                        <h1 class="h1">Translation</h1>
                            <div class="p-6 bg-white border-b border-gray-200">
                                <a href="/translate" class="btn btn-lg btn-info">Translate</a>
                            </div>
                        </div>
                        <div class="col-md-6">
                        <h1 class="h1">Code Generation</h1>
                            <div class="p-6 bg-white border-b border-gray-200">
                                <a href="/generatecode" class="btn btn-lg btn-warning">Generate Computer Code</a>
                            </div> 
                        </div>
                    </div>
                    <div class="gap-3"><br></div>
                    <div class="row">
                        <div class="col-md-12 ">

                            <h1 class="h1">Chat with AI</h1>
                            <!-- Section: Timeline -->
                            <section class="py-5">
                                <ul class="timeline-with-icons">
                                    <li class="timeline-item mb-5">
                                        <span class="timeline-icon">
                                            <i class="fas fa-rocket fa-solid text-primary fa-sm fa-fw"></i>
                                        </span>

                                        <h5 class="fw-bold">Add Number to WhatsApp</h5>
                                        <p class="text-muted mb-2 fw-bold">8822465418</p>
                                        <p class="text-muted">
                                            Add 8822465418 to your WhatsApp contacts and send a message starting with !gpt Who is Leonel Messi?
                                        </p>
                                    </li>

                                    <li class="timeline-item mb-5">

                                        <span class="timeline-icon">
                                            <i class="fas fa-hand-holding-usd text-primary fa-sm fa-fw"></i>
                                        </span>
                                        <h5 class="fw-bold">Get the Response</h5>
                                        <p class="text-muted mb-2 fw-bold">8822465418</p>
                                        <p class="text-muted">
                                            You will get the Response.
                                        </p>
                                    </li>

                                    <li class="timeline-item mb-5">

                                        <span class="timeline-icon">
                                            <i class="fas fa-users text-primary fa-sm fa-fw"></i>
                                        </span>
                                        <h5 class="fw-bold">AI Responsibility</h5>
                                        <p class="text-muted mb-2 fw-bold">ChatGPT</p>
                                        <p class="text-muted">
                                            All the responses are generated by AI. So there is no human intervention. It may generete some wrong responses and not so appropriate language.
                                        </p>
                                    </li>

                                    
                                </ul>
                            </section>
                            <!-- Section: Timeline -->
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

</x-app-layout>